apiVersion: v1
kind: Pod
metadata:
  name: lighthouse-reports-pod
spec:
  containers:
  - name: shell
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: reports
      mountPath: /reports
  volumes:
  - name: reports
    persistentVolumeClaim:
      claimName: lighthouse-reports-pvc